import { registerEnumType } from "type-graphql";

export enum RoleEnum {
  TENANT = "TENANT",
  PROPERTY_OWNER = "PROPERTY_OWNER",
  ADMIN = "ADMIN",
}

export enum PermissionEnum {
  READ_USERS = "READ_USERS",
  WRITE_USERS = "WRITE_USERS",
  DELETE_USERS = "DELETE_USERS",
  READ_PROPERTIES = "READ_PROPERTIES",
  WRITE_PROPERTIES = "WRITE_PROPERTIES",
  DELETE_PROPERTIES = "DELETE_PROPERTIES",
  MANAGE_VERIFICATIONS = "MANAGE_VERIFICATIONS",
  VIEW_ANALYTICS = "VIEW_ANALYTICS",
  SUPER_ADMIN = "SUPER_ADMIN",
}

export enum ProviderEnum {
  EMAIL = "EMAIL",
  GOOGLE = "GOOGLE",
  FACEBOOK = "FACEBOOK",
  LINKEDIN = "LINKEDIN",
}

export enum UserStatus {
  ACTIVE = "ACTIVE",
  SUSPENDED = "SUSPENDED",
  BANNED = "BANNED",
  PENDING_VERIFICATION = "PENDING_VERIFICATION",
}

export enum PropertyStatus {
  DRAFT = "DRAFT",
  PENDING_REVIEW = "PENDING_REVIEW",
  ACTIVE = "ACTIVE",
  RENTED = "RENTED",
  INACTIVE = "INACTIVE",
  REJECTED = "REJECTED",
  SUSPENDED = "SUSPENDED",
}

export enum PropertyType {
  BUNGALOW = "BUNGALOW",
  TWO_STORY = "TWO_STORY",
  THREE_STORY = "THREE_STORY",
  FOUR_STORY = "FOUR_STORY",
  SIX_PLUS_STORY = "SIX_PLUS_STORY",
  APARTMENT = "APARTMENT",
  DUPLEX = "DUPLEX",
  MANSION = "MANSION",
}

export enum RoomType {
  STUDIO = "STUDIO",
  ONE_BEDROOM = "ONE_BEDROOM",
  TWO_BEDROOM = "TWO_BEDROOM",
  THREE_BEDROOM = "THREE_BEDROOM",
  FOUR_BEDROOM = "FOUR_BEDROOM",
  FIVE_PLUS_BEDROOM = "FIVE_PLUS_BEDROOM",
  SELF_CONTAIN = "SELF_CONTAIN",
}

export enum RentalPeriod {
  WEEKLY = "WEEKLY",
  MONTHLY = "MONTHLY",
  QUARTERLY = "QUARTERLY",
  YEARLY = "YEARLY",
}

export enum DayOfWeek {
  MONDAY = "MONDAY",
  TUESDAY = "TUESDAY",
  WEDNESDAY = "WEDNESDAY",
  THURSDAY = "THURSDAY",
  FRIDAY = "FRIDAY",
  SATURDAY = "SATURDAY",
  SUNDAY = "SUNDAY",
}

export enum DocumentType {
  NIN = "NIN",
  DRIVERS_LICENSE = "DRIVERS_LICENSE",
  INTERNATIONAL_PASSPORT = "INTERNATIONAL_PASSPORT",
}

export enum VerificationStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  EXPIRED = "EXPIRED",
}

export enum TokenType {
  EMAIL_VERIFICATION = "EMAIL_VERIFICATION",
  PASSWORD_RESET = "PASSWORD_RESET",
  PHONE_VERIFICATION = "PHONE_VERIFICATION",
}

export enum MessageType {
  TEXT = "TEXT",
  IMAGE = "IMAGE",
  DOCUMENT = "DOCUMENT",
  SYSTEM = "SYSTEM",
}

export enum NotificationType {
  PROPERTY_APPROVED = "PROPERTY_APPROVED",
  PROPERTY_REJECTED = "PROPERTY_REJECTED",
  NEW_MESSAGE = "NEW_MESSAGE",
  PROPERTY_LIKED = "PROPERTY_LIKED",
  PROPERTY_VIEWED = "PROPERTY_VIEWED",
  VERIFICATION_APPROVED = "VERIFICATION_APPROVED",
  VERIFICATION_REJECTED = "VERIFICATION_REJECTED",
  ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED",
  ACCOUNT_REACTIVATED = "ACCOUNT_REACTIVATED",
  PROPERTY_INQUIRY = "PROPERTY_INQUIRY",
  SYSTEM_UPDATE = "SYSTEM_UPDATE",
}
